"""
Attrs resource trees and cattrs codecs for the Kubernetes compiler.
"""

from __future__ import annotations

from polyad_types.resources.base import Resource as Resource
from polyad_types.resources.capacity import CapacityNodeStatus as CapacityNodeStatus
from polyad_types.resources.capacity import CapacityStatus as CapacityStatus
from polyad_types.resources.capacity import PodSet as PodSet
from polyad_types.resources.capacity import PodTemplateReference as PodTemplateReference
from polyad_types.resources.capacity import ProvisioningRequestSpec as ProvisioningRequestSpec
from polyad_types.resources.codec import converter as converter
from polyad_types.resources.codec import encode_body as encode_body
from polyad_types.resources.codec import from_document as from_document
from polyad_types.resources.codec import to_document as to_document
from polyad_types.resources.common import AST as AST
from polyad_types.resources.common import GROUP as GROUP
from polyad_types.resources.common import VERSION as VERSION
from polyad_types.resources.common import DeleteOptions as DeleteOptions
from polyad_types.resources.common import ObjectMeta as ObjectMeta
from polyad_types.resources.common import OwnerReference as OwnerReference
from polyad_types.resources.common import ResourceType as ResourceType
from polyad_types.resources.common import StatusPatch as StatusPatch
from polyad_types.resources.common import UIDPreconditions as UIDPreconditions
from polyad_types.resources.infrastructure import Dragonfly as Dragonfly
from polyad_types.resources.infrastructure import PodTemplateResource as PodTemplateResource
from polyad_types.resources.infrastructure import PostgreSQLCluster as PostgreSQLCluster
from polyad_types.resources.infrastructure import ProvisioningRequest as ProvisioningRequest
from polyad_types.resources.istio import AuthorizationPolicy as AuthorizationPolicy
from polyad_types.resources.istio import DestinationRule as DestinationRule
from polyad_types.resources.istio import PeerAuthentication as PeerAuthentication
from polyad_types.resources.istio import VirtualService as VirtualService
from polyad_types.resources.kubernetes import ConfigMap as ConfigMap
from polyad_types.resources.kubernetes import DaemonSet as DaemonSet
from polyad_types.resources.kubernetes import DaemonSetSpec as DaemonSetSpec
from polyad_types.resources.kubernetes import Deployment as Deployment
from polyad_types.resources.kubernetes import DeploymentSpec as DeploymentSpec
from polyad_types.resources.kubernetes import DeploymentStrategy as DeploymentStrategy
from polyad_types.resources.kubernetes import Job as Job
from polyad_types.resources.kubernetes import JobSpec as JobSpec
from polyad_types.resources.kubernetes import LabelSelector as LabelSelector
from polyad_types.resources.kubernetes import Lease as Lease
from polyad_types.resources.kubernetes import LeaseSpec as LeaseSpec
from polyad_types.resources.kubernetes import NetworkPolicy as NetworkPolicy
from polyad_types.resources.kubernetes import PersistentVolumeClaim as PersistentVolumeClaim
from polyad_types.resources.kubernetes import Pod as Pod
from polyad_types.resources.kubernetes import PodTemplate as PodTemplate
from polyad_types.resources.kubernetes import ReplicaSet as ReplicaSet
from polyad_types.resources.kubernetes import Secret as Secret
from polyad_types.resources.kubernetes import Service as Service
from polyad_types.resources.kubernetes import ServiceAccount as ServiceAccount
from polyad_types.resources.kubernetes import StatefulSet as StatefulSet
from polyad_types.resources.kubernetes import StatefulSetSpec as StatefulSetSpec
from polyad_types.resources.mutations import Budget as Budget
from polyad_types.resources.mutations import BudgetDelta as BudgetDelta
from polyad_types.resources.mutations import Independence as Independence
from polyad_types.resources.mutations import Mutation as Mutation
from polyad_types.resources.mutations import MutationPlan as MutationPlan
from polyad_types.resources.mutations import Ordering as Ordering
from polyad_types.resources.mutations import Precondition as Precondition
from polyad_types.resources.mutations import Scope as Scope
from polyad_types.resources.polyad import Activation as Activation
from polyad_types.resources.polyad import Composition as Composition
from polyad_types.resources.polyad import Daemon as Daemon
from polyad_types.resources.polyad import DragonflyPool as DragonflyPool
from polyad_types.resources.polyad import Gate as Gate
from polyad_types.resources.polyad import Graph as Graph
from polyad_types.resources.polyad import GraphRule as GraphRule
from polyad_types.resources.polyad import OperatorPool as OperatorPool
from polyad_types.resources.polyad import PolyGraph as PolyGraph
from polyad_types.resources.polyad import RemoteScale as RemoteScale
from polyad_types.resources.polyad import ReplicaGroup as ReplicaGroup
from polyad_types.resources.polyad import ResourceDefinition as ResourceDefinition
from polyad_types.resources.polyad import Rewrite as Rewrite
from polyad_types.resources.polyad import ShutdownPolicy as ShutdownPolicy
from polyad_types.resources.polyad import TemporaryConnection as TemporaryConnection
from polyad_types.resources.polyad import Workload as Workload
from polyad_types.resources.registry import AUXILIARY_KINDS as AUXILIARY_KINDS
from polyad_types.resources.registry import BOUNDARY_KINDS as BOUNDARY_KINDS
from polyad_types.resources.registry import CAPACITY_KINDS as CAPACITY_KINDS
from polyad_types.resources.registry import NETWORK_POLICY_KINDS as NETWORK_POLICY_KINDS
from polyad_types.resources.registry import RESOURCE_TYPES as RESOURCE_TYPES
from polyad_types.resources.status import AdmissionMetrics as AdmissionMetrics
from polyad_types.resources.status import ConnectionMetrics as ConnectionMetrics
from polyad_types.resources.status import ExecutionMetrics as ExecutionMetrics
from polyad_types.resources.status import GraphMetrics as GraphMetrics
from polyad_types.resources.status import LayerMetrics as LayerMetrics
from polyad_types.resources.status import NodeCounts as NodeCounts
from polyad_types.resources.status import PhaseCounts as PhaseCounts
from polyad_types.resources.status import ResourceCounts as ResourceCounts
from polyad_types.resources.status import ResourceMetrics as ResourceMetrics
from polyad_types.resources.status import RollupMetrics as RollupMetrics
from polyad_types.resources.status import SubgraphMetrics as SubgraphMetrics
from polyad_types.resources.status import TopologyMetrics as TopologyMetrics
