{{- $values := include "polyad.benchmarks.values" . | fromJson -}}
{{- $context := merge (dict "Values" $values) (omit .Subcharts.polyadResources "Values") -}}
{{- include "polyad.resources.render" $context -}}
