{{- if and .Values.api.enabled .Values.api.key }}
{{- if .Values.api.existingSecret }}{{ fail "api.key and api.existingSecret are mutually exclusive" }}{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-polyad-api
type: Opaque
stringData:
  token: {{ .Values.api.key | quote }}
{{- end }}
{{- if and .Values.events.enabled .Values.events.key }}
{{- if .Values.events.existingSecret }}{{ fail "events.key and events.existingSecret are mutually exclusive" }}{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-polyad-events
type: Opaque
stringData:
  token: {{ .Values.events.key | quote }}
{{- end }}
