{{- if .Values.dragonfly.enabled }}
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: {{ .Release.Name }}-queue
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: polyad
spec:
  image: {{ .Values.dragonfly.image | quote }}
  imagePullPolicy: IfNotPresent
  replicas: {{ ternary .Values.dragonfly.ha.replicas 1 .Values.dragonfly.ha.enabled }}
  args:
    - --proactor_threads=1
    - --maxmemory=256mb
    - --cache_mode=false
    - --dbfilename=dump
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  {{- if .Values.dragonfly.ha.enabled }}
  enableReplicationReadinessGate: true
  pdb:
    maxUnavailable: 1
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ .Release.Name }}-queue
          topologyKey: {{ .Values.dragonfly.ha.topologyKey | quote }}
  {{- end }}
  {{- if .Values.dragonfly.persistence.enabled }}
  snapshot:
    cron: '*/5 * * * *'
    persistentVolumeClaimSpec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: {{ .Values.dragonfly.persistence.size }}
      {{- if .Values.dragonfly.persistence.storageClass }}
      storageClassName: {{ .Values.dragonfly.persistence.storageClass | quote }}
      {{- end }}
  {{- end }}
{{- end }}
