{{- $ := merge (dict "Values" (include "polyad.profileValues" . | fromJson)) (omit . "Values") -}}
{{- with $ -}}
{{- if .Values.events.istio.enabled }}
{{- if not (and .Values.events.enabled .Values.events.rebalance.enabled .Values.mesh.operator.enabled (eq .Values.events.rebalance.routing "Service")) }}{{ fail "events.istio requires events, rebalancing, mesh.operator and Service routing" }}{{ end }}
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-polyad-events
spec:
  host: {{ printf "%s-polyad-events.%s.svc.cluster.local" .Release.Name .Release.Namespace | quote }}
  exportTo: ["*"]
  trafficPolicy:
    loadBalancer:
      simple: {{ .Values.events.istio.loadBalancer }}
      warmup:
        duration: {{ printf "%vs" .Values.events.istio.warmupSeconds | quote }}
      {{- if .Values.mesh.multicluster.routing.enabled }}
      localityLbSetting:
        enabled: true
        {{- if eq .Values.mesh.multicluster.routing.mode "Failover" }}
        failover:
          {{- toYaml .Values.mesh.multicluster.routing.failover | nindent 10 }}
        {{- else if eq .Values.mesh.multicluster.routing.mode "Distributed" }}
        distribute:
          {{- toYaml .Values.mesh.multicluster.routing.distribute | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- if .Values.mesh.multicluster.routing.enabled }}
    outlierDetection:
      consecutive5xxErrors: {{ .Values.mesh.multicluster.routing.consecutive5xxErrors }}
      interval: {{ printf "%vs" .Values.mesh.multicluster.routing.intervalSeconds | quote }}
      baseEjectionTime: {{ printf "%vs" .Values.mesh.multicluster.routing.baseEjectionSeconds | quote }}
      maxEjectionPercent: {{ .Values.mesh.multicluster.routing.maxEjectionPercent }}
    {{- end }}
{{- end }}
{{- end -}}
