{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-polyad-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: polyad
    polyad.astrivant.com/component: {{ ternary "gateway" "dense" (eq .Values.architecture.mode "Distributed") }}
  ports:
    - name: http
      port: 8090
      targetPort: composition
{{- end }}
