{{- $ := merge (dict "Values" (include "polyad.profileValues" . | fromJson)) (omit . "Values") -}}
{{- with $ -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-polyad
{{- end -}}
