apiVersion: v2
name: polyad
description: Kubernetes operator for scheduling workloads through graphs
type: application
version: 0.0.1-alpha2
appVersion: 0.0.1-alpha2
kubeVersion: '>=1.30.0-0'
dependencies:
  - name: dragonfly-operator
    alias: dragonflyOperator
    version: v1.6.1
    repository: oci://ghcr.io/dragonflydb/dragonfly-operator/helm
    condition: dragonfly.enabled
  - name: base
    alias: istioBase
    version: 1.30.4
    repository: https://istio-release.storage.googleapis.com/charts
    condition: mesh.install
  - name: istiod
    version: 1.30.4
    repository: https://istio-release.storage.googleapis.com/charts
    condition: mesh.install
  - name: gateway
    alias: istioIngress
    version: 1.30.4
    repository: https://istio-release.storage.googleapis.com/charts
    condition: mesh.ingress.enabled
