apiVersion: v2
name: polyad
description: >-
  Deploy Polyad's graph orchestration control plane with single-replica or HA
  profiles, multicluster coordination, autoscaling and optional storage and telemetry
type: application
version: 0.0.1-alpha3
appVersion: 0.0.1-alpha3
kubeVersion: '>=1.30.0-0'
dependencies:
  - name: polyad-crds
    alias: polyadResources
    version: 0.0.1-alpha3
    repository: file://../polyad-crds
    condition: polyadResources.enabled
  - name: keda
    alias: kedaOperator
    version: 2.20.2
    repository: https://kedacore.github.io/charts
    condition: keda.install
  - name: dragonfly-operator
    alias: dragonflyOperator
    version: v1.6.1
    repository: oci://ghcr.io/dragonflydb/dragonfly-operator/helm
    condition: dragonfly.enabled
  - name: base
    alias: istioBase
    version: 1.30.4
    repository: https://istio-release.storage.googleapis.com/charts
    condition: mesh.install
  - name: istiod
    version: 1.30.4
    repository: https://istio-release.storage.googleapis.com/charts
    condition: mesh.install
  - name: gateway
    alias: istioIngress
    version: 1.30.4
    repository: https://istio-release.storage.googleapis.com/charts
    condition: mesh.ingress.enabled
  - name: gateway
    alias: istioEastWest
    version: 1.30.4
    repository: https://istio-release.storage.googleapis.com/charts
    condition: mesh.multicluster.eastWest.enabled
