{{- $ := merge (dict "Values" (include "polyad.profileValues" . | fromJson)) (omit . "Values") -}}
{{- with $ -}}
{{- if .Values.worker.enabled }}
{{ include "polyad.operatorDeployment" . }}
{{- end }}
{{- end -}}
